name: Deploy Dev.abirah.pk

on:
  push:
    branches:
      - "master"


jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Codeaa
        uses: actions/checkout@v2
      - name: Deploy to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@main
        with:
          server: ${{ secrets.CPANEL_URL }}
          username: ${{ secrets.CPANEL_USERNAME }}
          password: ${{ secrets.CPANEL_PASSWORD }}
