name: Deploy Dev.abirah.pk

on:
  push:
    branches:
      - "master"


jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Codeaa
        uses: actions/checkout@v2
      - name: SSH into cPanel Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CPANEL_URL }}
          username: ${{ secrets.SSH_USERNAME }}  # You need to set up SSH keys or use a secret with your SSH password
          password: ${{ secrets.SSH_PASSWORD }}  # Alternatively, you can use a password
          script: |
            ls_result=$(ls)

            echo "List of files and directories:"
            echo "$ls_result"

